backend:
  name: github
  repo: zampamaniaofficial-svg/zampamania # Es: zampamania/zampamania-website
  branch: main

# Gestione Media Predefinita
media_folder: "immagini_cani"
public_folder: "/immagini_cani"

collections:
  - name: "articoli"
    label: "Articoli"
    folder: "articoli"
    create: true
    slug: "{{slug}}"
    extension: "html"
    format: "raw"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data Pubblicazione", name: "date", widget: "datetime", date_format: "DD/MM/YYYY", time_format: false }
      - { label: "Descrizione SEO / Meta", name: "description", widget: "text" }
      - { label: "Immagine Cane", name: "image_cani", widget: "image", required: false, media_folder: "immagini_cani", public_folder: "/immagini_cani" }
      - { label: "Immagine Gatto", name: "image_gatti", widget: "image", required: false, media_folder: "immagini_gatti", public_folder: "/immagini_gatti" }
      - { label: "Contenuto", name: "body", widget: "markdown" }
